from pathlib import Path

BASE_DIR =Path(__file__).resolve().parents[2]

DATA_DIR = BASE_DIR / 'data'
RAW_DIR = DATA_DIR / 'raw'
PROCESSED_DIR = DATA_DIR / 'processed'
INTERIM_DIR = DATA_DIR / 'interim'
METADATA_DIR = DATA_DIR / 'metadata'

REPORTS_DIR = BASE_DIR / 'reports'
FIGURES_DIR = REPORTS_DIR / 'figures'
TABLES_DIR = REPORTS_DIR / 'tables'
SUMMARIES_DIR = REPORTS_DIR / 'summaries'

ARTIFACTS_DIR = BASE_DIR / 'artifacts'
MODELS_DIR = ARTIFACTS_DIR / 'models'
METRICS_DIR = ARTIFACTS_DIR / 'metrics'
FEATURE_LISTS_DIR = ARTIFACTS_DIR / 'feature_lists'

RAW_FILE_NAME = 'RAWBOARDMDF6393074229807150656_5759740155664354753 - ORIGIN.xlsx'
RAW_FILE_PATH = RAW_DIR / RAW_FILE_NAME

SHEET_NAME = 'FQTTS_EXCEL_EXPORT'

HEADER_ROW_FOR_TECHNICAL_NAMES = 1

RANDOM_STATE = 42
TEST_SIZE= 0.2
VALID_SIZE = 0.2

MAX_MISSING_RATIO_PER_FEATURE =0.40
DROP_ROWS_WITH_MISSING_PRIMARY_TARGETS = True

FLATTENED_FILE_PATH = INTERIM_DIR/'mdf1_flattened_data.csv'
CLEANED_FILE_PATH = INTERIM_DIR/'mdf1_cleaned_data.csv'
COLUMN_MAPPING_FILE_PATH = METADATA_DIR / 'column_mappings.csv'
VALIDATION_REPORT_PATH = METADATA_DIR/'validation_report.json'
AUDIT_SUMMARY_PATH = SUMMARIES_DIR /'initial_data_audit.txt'
DROP_ROWS_WITH_MISSING_PRIMARY_TARGET = True

for path in [
    RAW_DIR, INTERIM_DIR, PROCESSED_DIR, METADATA_DIR,
    REPORTS_DIR, FIGURES_DIR, TABLES_DIR, SUMMARIES_DIR,
    ARTIFACTS_DIR, MODELS_DIR, METRICS_DIR, FEATURE_LISTS_DIR
]:
    path.mkdir(parents=True, exist_ok=True)
